---
root: true

extends:
  - airbnb-base
  - plugin:import/errors
  - sketch

env:
  node: true
  
globals:
  CGColorCreateGenericRGB: true
  CGRectGetMaxY: true
  COSAlertWindow: true
  NSOffState: true
  NSOnState: true
  NSSwitchButton: true
  NSHomeDirectory: true

settings:
  import/core-modules: [
    'sketch/ui',
    'sketch/dom',
    'sketch/settings'
  ]

rules:
  no-param-reassign: off
  consistent-return: off
  import/prefer-default-export: off
  import/no-dynamic-require: off
  global-require: off
  no-console: off
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: true
  template-curly-spacing:
    - error
    - always
  semi:
    - error
    - never
  comma-dangle:
    - error
    - never
  