---
root: true

extends:
  - sketch
  - airbnb
  - plugin:import/errors

globals:
  CGColorCreateGenericRGB: true
  CGRectGetMaxY: true
  COSAlertWindow: true
  NSOffState: true
  NSOnState: true
  NSSwitchButton: true
  NSHomeDirectory: true
  NSStringPboardType: true
  document: true
  window: true

plugins:
  - react

parser: babel-eslint

settings:
  import/resolver:
    webpack:
      config: 'webpack.skpm.config.js'
    node:
      paths:
        - src
  import/core-modules:
    - sketch/ui
    - sketch/dom
    - sketch/settings

rules:
  import/prefer-default-export: off
  no-param-reassign: off
  no-console: off
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: true
  object-curly-spacing:
    - error
    - always
  array-bracket-spacing:
    - error
    - always
  template-curly-spacing:
    - error
    - always
  semi:
    - error
    - never
  comma-dangle:
    - error
    - never
  keyword-spacing:
    - error
    - before: true
      after: true
      overrides:
        return:
          after: true
        throw:
          after: true
        case:
          after: true
  react/jsx-curly-spacing:
    - error
    - when: always
      attributes:
        allowMultiline: true
      children: true