extends:
  - sketch
  - airbnb
  - plugin:import/errors

globals:
  CGColorCreateGenericRGB: true
  CGRectGetMaxY: true
  COSAlertWindow: true
  NSOffState: true
  NSOnState: true
  NSSwitchButton: true
  NSHomeDirectory: true
  NSStringPboardType: true
  document: true
  window: true

parser: babel-eslint

settings:
  import/resolver:
    node:
      paths:
        - src
  import/core-modules:
    - sketch/ui
    - sketch/dom
    - sketch/settings

rules:
  # bc it's silly
  no-console: off

  # bc mutation
  no-param-reassign: off

  # bc its annoying
  import/prefer-default-export: off
  react/destructuring-assignment: off

  # bc it's easier to read
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: true
  array-bracket-spacing:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  template-curly-spacing:
    - error
    - always
  react/jsx-curly-spacing:
    - error
    - when: always
      attributes:
        allowMultiline: true
      children: true

  # bc I have ocd
  semi:
    - error
    - never
  comma-dangle:
    - error
    - never
